[package]
name = "audiopass"
version = "0.1.0"
description = "AudioPass is a Linux desktop app that plays local audio files through a virtual microphone."
authors = ["Vishnu Nithin Reddy"]
edition = "2024"



[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = "symbols" 

[dependencies]
eframe = { version = "0.36.1" }
# 0_3_49 lets me use buffer.requested() for frame count pipewire recommends when writing to source stream (src/backend/pipewire/virtual_mic.rs)
# (and >=0_3_44 lets me use pipewire::keys::TARGET_OBJECT to create stream targeting physical mic (or any node I guess))
pipewire = { version = "0.10.1", features = ["v0_3_49"] }
ringbuf = { version = "0.5.1"}
rfd = { version = "0.17.2" }
