[package]
name = "audiopass"
version = "0.1.0"
description = "AudioPass is a Linux desktop app that plays local audio through a virtual microphone."
license = "MIT"
authors = ["Vishnu Nithin Reddy"]
edition = "2024"
publish = false


[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = "symbols"

[dependencies]
eframe = { version = "0.36" }
pipewire = { version = "0.10.1", features = ["v0_3_49"] } # 0_3_49 for buffer.requested() for frame count value (backend/pipewire/virtual_mic.rs)
ringbuf = { version = "0.5.2" }
rfd = { version = "0.17.2" }
uuid = { version = "=1.26.0", features = ["serde", "v4"] }
serde = { version = "1.0.229" }
serde_json = { version = "1.0.151" }
tokio = { version = "1.50.0", features = [
  "fs",
  "rt-multi-thread",
  "sync",
  "time",
] }
egui-phosphor = { version = "0.14.0" }
single-instance = { version = "0.3.3" }
# not used until local playback is good to go, just complicates third party notices till then
# rodio = { version = "0.22.2" }
