name: Build

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build AudioPass
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Print glibc version
        run: ldd --version

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libpipewire-0.3-dev libasound2-dev

      - name: Build AudioPass
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: audiopass
          path: target/release/audiopass
          retention-days: 1
